name: Build 

on:
  push:
    branches: [ Production]
  pull_request:
    branches: [ Production ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make all
      run:  make all -C 3_Implementation/
